---
namespace: ai-agent
registry: image-registry.openshift-image-registry.svc:5000
application_name: ai-agent
git_url: https://github.com/wkulhanek/etx-agentic-ai.git
git_revision: main
git_subdirectory: code
agent_endpoint: http://ai-agent:8000/report-failure

# Agent Configuration
agentConfig:
  clientTimeout: "600.0"
  llamaStackUrl: "http://llamastack-with-config-service.llama-stack.svc.cluster.local:8321"
  # llamaStackUrl: "http://llamastack-with-config-service.default.svc.cluster.local:8321"
  maxInferIterations: "50"
  maxTokens: "5000"
  modelId: "llama-4-scout-17b-16e-w4a16"
  temperature: "0.0"

# Service Account configuration
serviceAccount:
  name: pipeline

# Role Binding configuration
roleBinding:
  name: openshift-pipelines-edit
  clusterRole: edit

# Job configuration
job:
  name: trigger-agent-service-build
  enabled: true

# Pipeline configuration
pipeline:
  name: agent-service-build
  timeout: 1h0m0s

# Workspace configuration
workspace:
  name: workspace
  storage: 3Gi

# Container images
images:
  cliTool: registry.redhat.io/openshift4/ose-cli:latest

