---
apiVersion: v1
kind: ConfigMap
metadata:
  name: time-slicing-config
  namespace: nvidia-gpu-operator
data:
    NVIDIA-L4: |-  # this must match node labels nvidia.com/gpu.product=NVIDIA-L40S and nvidia.com/device-plugin.config=NVIDIA-L40S
      version: v1
      flags:
        migStrategy: none
      sharing:
        timeSlicing:
          resources:
          - name: nvidia.com/gpu
            replicas: 8
